sudo: required
dist: trusty
addons:
  apt:
    packages:
      - texlive
      - texlive-base
      - texlive-latex-extra
      - texlive-bibtex-extra
      - texlive-lang-german
      - texlive-fonts-extra
      - biber
script:
  - pdflatex main.tex
  - biber main
  - makeglossaries main
  - pdflatex main.tex
