sudo: required
dist: trusty
addons:
  apt:
    packages:
      - texlive
      - texlive-latex-extra
      - texlive-lang-german
      - texlive-opensans
script:
  - pdflatex main.tex
  - biber main
  - makeglossaries main
  - pdflatex main.tex
