sudo: required
dist: trusty
addons:
  apt:
    packages:
      - texlive
      - texlive-base
      - texlive-latex-extra
      - texlive-bibtex-extra
      - texlive-lang-german
      - texlive-fonts-extra
      - biber
script:
  - pdflatex main.tex
  - biber main
  - makeglossaries main
  - pdflatex main.tex

deploy:
  provider: s3
  access_key_id: "$AWS_KEY"
  secret_access_key: "$AWS_SECRET"
  bucket: "stefis_idpa"
  file: "main.pdf"
